name: Cloudflare Pages Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo (Optional - Cloudflare can handle this)
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build (No need for explicit build here as Cloudflare will do it)
        run: echo "Building handled by Cloudflare Pages"
