name: Cloudflare Pages Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      # - name: Create cname file
      #   run: echo "demo.gh.jimmyliao.net" > static/CNAME

      - name: Update robot.txt
        run: |
                    echo -e "User-agent: *\nDisallow: /" > static/robots.txt

      - name: Setup Hugo (Optional - Cloudflare can handle this)
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build (No need for explicit build here as Cloudflare will do it)
        run: echo "Building handled by Cloudflare Pages"
